apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: strapi
bases:
- ../workload
images:
- name: devlaunchers/cms-api
  newName: devlaunchers/cms-api
  newTag: 7f2cc59-202106131700 # {"$imagepolicy": "strapi:strapi:tag"}
