apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: strapi
bases:
- ../workload
images:
- name: devlaunchers/cms-api
  newName: devlaunchers/cms-api
  newTag: 4781252-202106092156 # {"$imagepolicy": "strapi:strapi:tag"}
