apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: strapi
bases:
- ../workload
- ./configmap.yaml
images:
- name: devlaunchers/cms-api
  newName: devlaunchers/cms-api
  newTag: e5b287a-202109262015 # {"$imagepolicy": "strapi:strapi:tag"}
