apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: strapi
bases:
- ../workload
- ./configmap.yaml
images:
- name: devlaunchers/cms-api
  newName: devlaunchers/cms-api
  newTag: f37d14d-202106171615 # {"$imagepolicy": "strapi:strapi:tag"}
