apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: strapi
bases:
- ../workload
- ./configmap.yaml
images:
- name: devlaunchers/cms-api
  newName: devlaunchers/cms-api
  newTag: b921e16-202107041844 # {"$imagepolicy": "strapi:strapi:tag"}
