apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: strapi
bases:
- ../workload
- ./configmap.yaml
images:
- name: devlaunchers/cms-api
  newName: devlaunchers/cms-api
  newTag: 1d6ccf8-202109200512 # {"$imagepolicy": "strapi:strapi:tag"}
