apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: strapi
bases:
- ../workload
images:
- name: devlaunchers/cms-api
  newName: devlaunchers/cms-api
  newTag: c9592db-202106040953 # {"$imagepolicy": "strapi:strapi:tag"}