apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: strapi
bases:
- ../workload
images:
- name: devlaunchers/cms-api
  newName: devlaunchers/cms-api
  newTag: 2b44528-202106052008 # {"$imagepolicy": "strapi:strapi:tag"}
