apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: strapi
bases:
- ../workload
images:
- name: devlaunchers/cms-api
  newName: devlaunchers/cms-api
  newTag: 8161f6a-202106041030 # {"$imagepolicy": "strapi:strapi:tag"}
