apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: strapi
bases:
- ../workload
resources:
  - deployment.yaml
images:
- name: devlaunchers/cms-api
  newName: devlaunchers/cms-api
  newTag: 1.0.2 # {"$imagepolicy": "strapi:strapi:tag"}
