apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: strapi
  name: strapi
  labels:
    app: strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
      - name: strapi
        image: devlaunchers/cms-api:latest
        ports:
        - containerPort: 1337
        env:
        - name: DATABASE_CLIENT
          value: postgres
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: postgres
              key: name
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: postgres
              key: host
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: postgres
              key: port
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres
              key: user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: strapi-config
              key: url
        resources:
          limits:
            cpu: 256m
            memory: 256Mi
          requests:
            cpu: 128m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /
            port: 1337
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 5
