apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strapi-pv-claim
  namespace: strapi
  labels:
    app: strapi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 10Gi